Link against libopenblas.lib on Windows
RubixML/Tensor pull request #24
Opened 2021-11-05 13:30 UTC by cmb69

Without a respective lib, linking would inevitably fail.  We also add
a check for cblas.h, and if either is not found, disable ext/tensor
with a respective warning.

See also <https://github.com/RubixML/Tensor/issues/22>.

2021-11-05 13:31 UTC, cmb69 commented
_**I have read the CLA Document and I hereby sign the CLA**_

2021-11-05 13:32 UTC, cmb69 commented
recheck

2021-11-12 21:03 UTC, andrewdalpino requested changes
Hey @cmb69 thanks so much for the help! Unfortunately, this file gets overwritten by the Zephir compiler so we need to add this logic to this build script for example https://github.com/RubixML/Tensor/blob/master/build-ext. Let me know if you would like to make the changes, otherwise I think I can probably do it.

Thank you again! Won't you join our group on Telegram? https://t.me/RubixML

2021-11-15 13:39 UTC, cmb69 commented
Ah, I see! I wouldn't know, though, how to adapt the build script. If you can do it, please go ahead. :)

2021-12-12 02:27 UTC, merged

2021-12-12 02:50 UTC, andrewdalpino commented
Hey @cmb69, I haven't been able to find the documentation to get an understanding of this or anything in the config.w32 file. From what I gather so far, it's Javascript with GNU Automake macros. However, the closest docs I found are here https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.70/autoconf.html#index-AC_005fCHECK_005fLIB but the macro signatures are different.

Can you explain what exactly is going on here? Again, this file is supposed to be handled by the Zephir compiler and I have been relying on it so far to give us the correct configuration. Thank you!